title: "Alex Moy – Electrical Engineering Portfolio"
description: >
  Embedded systems • PCB design • FPGA • Signal Processing • Circuit Debugging

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

logo: /images/hs.png

show_downloads: false
